blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/devswiftzone/swift.nvim/security/advisories/new
    about: Please use the private advisory form for security reports.
  - name: Documentation questions
    url: https://github.com/devswiftzone/swift.nvim#-documentation
    about: Review the documentation index for guides and examples before opening an issue.
