local M = {}

local utils = require("swift.core.utils")
local config = require("swift.core.config")

local current_job_id = nil

-- Generates a temporary HTML file and opens it in the browser
function M.run_static(preview_name, bufnr)
  local project_root = utils.get_buffer_dir()

  vim.notify("Building static HTMLKit preview: " .. preview_name, vim.log.levels.INFO, { title = "swift.nvim" })

  -- Here we assume there's a way to output the preview to HTML.
  -- As a placeholder, we use a custom swift script or a specific target.
  -- In a real Vapor app, this might involve running a specific command that
  -- renders the view and outputs HTML.

  -- For the sake of the architecture, let's create a temporary HTML file
  -- to demonstrate the opening functionality.
  local temp_html = vim.fn.tempname() .. ".html"

  -- Mock generation of HTML
  local html_content = string.format(
    [[
    <!DOCTYPE html>
    <html>
    <head><title>Static Preview: %s</title></head>
    <body>
      <h1>Preview: %s</h1>
      <p>This is a static render generated by swift.nvim.</p>
      <p>In a real project, this would be the output of your HTMLKit view.</p>
    </body>
    </html>
  ]],
    preview_name,
    preview_name
  )

  local file = io.open(temp_html, "w")
  if file then
    file:write(html_content)
    file:close()
  end

  -- Open in default browser
  local open_cmd = "open" -- macOS
  if vim.fn.has("linux") == 1 then
    open_cmd = "xdg-open"
  elseif vim.fn.has("win32") == 1 then
    open_cmd = "start"
  end

  vim.system({ open_cmd, temp_html }, {}, function(obj)
    if obj.code == 0 then
      vim.notify("Static preview opened in browser.", vim.log.levels.INFO, { title = "swift.nvim" })
    else
      vim.notify("Failed to open browser.", vim.log.levels.ERROR, { title = "swift.nvim" })
    end
  end)
end

-- Starts a local server or script for interactive live-reload
function M.run_interactive(preview_name, bufnr)
  local project_root = utils.get_buffer_dir()
  local port = config.get_feature("preview_panel").server_port or 8080

  if current_job_id then
    vim.notify("Stopping existing interactive preview...", vim.log.levels.INFO, { title = "swift.nvim" })
    vim.fn.jobstop(current_job_id)
    current_job_id = nil
  end

  vim.notify("Starting interactive server for: " .. preview_name, vim.log.levels.INFO, { title = "swift.nvim" })

  -- Mock server start command.
  -- In reality, this would be `swift run Run --port 8080` or similar.
  local cmd = { "swift", "run" }

  current_job_id = vim.fn.jobstart(cmd, {
    cwd = project_root,
    on_stdout = function(_, data)
      if data and #data > 0 and data[1] ~= "" then
        -- You could log this if needed
      end
    end,
    on_exit = function(_, code)
      current_job_id = nil
      if code ~= 0 and code ~= 143 then -- 143 is SIGTERM
        vim.notify("Interactive server exited with code " .. code, vim.log.levels.WARN, { title = "swift.nvim" })
      end
    end,
  })

  -- Wait a bit for server to start then open browser
  vim.defer_fn(function()
    local url = "http://localhost:" .. port
    local open_cmd = "open" -- macOS
    if vim.fn.has("linux") == 1 then
      open_cmd = "xdg-open"
    end

    if config.get_feature("preview_panel").open_browser then
      vim.system({ open_cmd, url })
      vim.notify("Opened interactive preview: " .. url, vim.log.levels.INFO, { title = "swift.nvim" })
    end
  end, 2000)
end

function M.stop_interactive()
  if current_job_id then
    vim.fn.jobstop(current_job_id)
    current_job_id = nil
    vim.notify("Interactive preview stopped.", vim.log.levels.INFO, { title = "swift.nvim" })
  end
end

return M
